version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
    schedule:
      interval: "daily"
    target-branch: "main"
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
    target-branch: "main"
