name: Lint and Test
on: 
  push:
    paths:
    - '**go**'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: v1.38
          args: -c .golangci.yml
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Cache dependencies
        id: cache-dep
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install dependencies
        if: steps.cache-dep.outputs.cache-hit != 'true'
        run: go mod download
      - name: Run test
        run: go test -v ./...
