name: Lint and Test
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.38
          args: -c .golangci.yml
